dependencies = []
incompatibilities = []

[metadata]
id = "org.modweaver.api"
version = "1.0.0"
title = "ModWeaver API"
authors = [
    "Ecorous",
    "reddust9",
    "Neko_Lover"
]
game_version = 1.5